import Head from "next/head";

import { LoginPage } from "@shared/simple";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage onSubmit={(f) => f} sent={false} loading={false} />
    </>
  );
}
