name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Go to package
        run: cd packages/react-ui

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        run: npm run chromatic
