name: DevCycle Code Usages

on:
  push:
    branches: [main]

jobs:
  dvc-code-usages:
    runs-on: ubuntu-latest
    name: Fetch DevCycle Code Usages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: DevCycle Feature Flag Code Usages
        uses: DevCycleHQ/feature-flag-code-usage-action@v1.1.0
        with:
          github-token: ${{ secrets.DVC_PAT }}
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
          project-key: my-first-project
