name: Omlet

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  omlet_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Omlet uses git history for analysis; disable shallow clone
          fetch-depth: 0

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Analyze
        run: npx omlet analyze
        env:
          OMLET_TOKEN: ${{ secrets.OMLET_TOKEN }}
